name: pair
description: A Pair class in dart that inspired Pair from java. Represents a generic pair of two values.
version: 0.1.2
repository: https://github.com/nandanurseptama/dart_pair

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
